import React from "react";

export const ingredientEmojis = {

  // Vegetables
  tomato: "🍅",
  onion: "🧅",
  potato: "🥔",
  carrot: "🥕",
  garlic: "🧄",
  ginger: "🫚",
  broccoli: "🥦",
  cauliflower: "🥦",
  cabbage: "🥬",
  spinach: "🥬",
  lettuce: "🥬",
  cucumber: "🥒",
  zucchini: "🥒",
  eggplant: "🍆",
  brinjal: "🍆",
  corn: "🌽",
  peas: "🫛",
  beans: "🫘",
  "green beans": "🫛",
  mushroom: "🍄",
  mushrooms: "🍄",
  pumpkin: "🎃",
  "sweet potato": "🍠",
  radish: "🥕",
  beetroot: "🫜",
  turnip: "🫜",
  celery: "🥬",
  asparagus: "🌱",
  okra: "🌱",
  ladyfinger: "🌱",
  "bell pepper": "🫑",
  capsicum: "🫑",
  pepper: "🌶️",
  chili: "🌶️",
  chilli: "🌶️",
  jalapeno: "🌶️",
  "green chili": "🌶️",
  "red chili": "🌶️",

  // Fruits
  apple: "🍎",
  banana: "🍌",
  orange: "🍊",
  lemon: "🍋",
  lime: "🍋",
  mango: "🥭",
  pineapple: "🍍",
  watermelon: "🍉",
  grapes: "🍇",
  strawberry: "🍓",
  strawberries: "🍓",
  blueberry: "🫐",
  blueberries: "🫐",
  peach: "🍑",
  pear: "🍐",
  cherry: "🍒",
  cherries: "🍒",
  kiwi: "🥝",
  coconut: "🥥",
  avocado: "🥑",
  papaya: "🥭",
  pomegranate: "🍎",

  // Meat
  chicken: "🍗",
  "chicken breast": "🍗",
  "chicken thighs": "🍗",
  beef: "🥩",
  steak: "🥩",
  pork: "🥩",
  bacon: "🥓",
  ham: "🍖",
  lamb: "🍖",
  mutton: "🍖",
  sausage: "🌭",
  sausages: "🌭",
  turkey: "🍗",

  // Seafood
  fish: "🐟",
  salmon: "🐟",
  tuna: "🐟",
  prawn: "🍤",
  prawns: "🍤",
  shrimp: "🍤",
  crab: "🦀",
  lobster: "🦞",
  squid: "🦑",
  octopus: "🐙",

  // Dairy & Eggs
  egg: "🥚",
  eggs: "🥚",
  milk: "🥛",
  cheese: "🧀",
  butter: "🧈",
  yogurt: "🥛",
  yoghurt: "🥛",
  cream: "🥛",
  "cream cheese": "🧀",
  paneer: "🧀",
  "cottage cheese": "🧀",
  ghee: "🧈",

  // Grains & Bakery
  rice: "🍚",
  basmati: "🍚",
  "basmati rice": "🍚",
  flour: "🌾",
  wheat: "🌾",
  atta: "🌾",
  "wheat flour": "🌾",
  oats: "🌾",
  oatmeal: "🥣",
  bread: "🍞",
  toast: "🍞",
  bun: "🍔",
  buns: "🍔",
  pasta: "🍝",
  spaghetti: "🍝",
  noodles: "🍜",
  vermicelli: "🍜",
  "rice flour": "🌾",
  "gram flour": "🌾",
  besan: "🌾",
  semolina: "🌾",
  suji: "🌾",
  rava: "🌾",
  poha: "🍚",

  // Fresh Indian herbs
  coriander: "🌿",
  cilantro: "🌿",
  "coriander leaves": "🌿",
  mint: "🌿",
  "mint leaves": "🌿",
  basil: "🌿",
  curry: "🌿",
  "curry leaves": "🌿",
  parsley: "🌿",
  fenugreek: "🌿",
  methi: "🌿",
  "methi leaves": "🌿",

  // Indian spices
  salt: "🧂",
  blacksalt: "🧂",
  "black salt": "🧂",
  cumin: "🌿",
  jeera: "🌿",
  "cumin seeds": "🌿",
  corianderpowder: "🌿",
  "coriander powder": "🌿",
  dhania: "🌿",
  turmeric: "🟡",
  haldi: "🟡",
  paprika: "🌶️",
  "red chili powder": "🌶️",
  "red chilli powder": "🌶️",
  "chili powder": "🌶️",
  "chilli powder": "🌶️",
  blackpepper: "⚫",
  "black pepper": "⚫",
  peppercorn: "⚫",
  mustard: "🌱",
  "mustard seeds": "🌱",
  rai: "🌱",
  cardamom: "🌿",
  elaichi: "🌿",
  cinnamon: "🪵",
  dalchini: "🪵",
  clove: "🌿",
  cloves: "🌿",
  laung: "🌿",
  bayleaf: "🍃",
  "bay leaf": "🍃",
  tejpatta: "🍃",
  staranise: "⭐",
  "star anise": "⭐",
  anise: "🌿",
  fennel: "🌿",
  saunf: "🌿",
  fenugreekseeds: "🌿",
  "fenugreek seeds": "🌿",
  asafoetida: "🌿",
  hing: "🌿",

  // Indian Masalas
  "garam masala": "🌿",
  "chicken masala": "🌶️",
  "chicken masala powder": "🌶️",
  "meat masala": "🌶️",
  "mutton masala": "🌶️",
  "fish masala": "🌶️",
  "paneer masala": "🌶️",
  "paneer tikka masala": "🌶️",
  "butter chicken masala": "🌶️",
  "biryani masala": "🌶️",
  "chaat masala": "🌿",
  "kitchen king masala": "🌿",
  "curry powder": "🌿",
  "curry masala": "🌿",
  "tandoori masala": "🌶️",
  "pav bhaji masala": "🌶️",
  "pav bhaji": "🌶️",
  "sambar powder": "🌶️",
  "sambar masala": "🌶️",
  "rasam powder": "🌶️",
  "rasam masala": "🌶️",
  "chole masala": "🌶️",
  "chana masala": "🌶️",
  "rajma masala": "🌶️",
  "dal masala": "🌿",
  amchur: "🥭",
  "amchur powder": "🥭",
  "dry mango powder": "🥭",

  // Pulses & Legumes
  dal: "🫘",
  "moong dal": "🫘",
  "masoor dal": "🫘",
  "toor dal": "🫘",
  "urad dal": "🫘",
  "chana dal": "🫘",
  moong: "🫘",
  masoor: "🫘",
  toor: "🫘",
  urad: "🫘",
  chickpeas: "🫘",
  "chick peas": "🫘",
  chana: "🫘",
  "kabuli chana": "🫘",
  rajma: "🫘",
  "kidney beans": "🫘",
  "black beans": "🫘",
  lobia: "🫘",
  "black eyed peas": "🫘",

  // Nuts & Seeds
  almond: "🌰",
  almonds: "🌰",
  peanut: "🥜",
  peanuts: "🥜",
  moongfali: "🥜",
  walnut: "🌰",
  walnuts: "🌰",
  cashew: "🥜",
  cashews: "🥜",
  kaju: "🥜",
  pistachio: "🥜",
  pistachios: "🥜",
  pista: "🥜",
  sesame: "🌱",
  til: "🌱",
  "sesame seeds": "🌱",
  "sunflower seeds": "🌻",
  flaxseed: "🌱",
  chia: "🌱",
  "chia seeds": "🌱",

  // Sauces & Condiments
  ketchup: "🍅",
  mayonnaise: "🥫",
  "soy sauce": "🥣",
  vinegar: "🍶",
  "hot sauce": "🌶️",
  "tomato sauce": "🍅",
  pickle: "🥒",
  pickles: "🥒",
  achar: "🥒",
  chutney: "🥣",
  "coconut milk": "🥥",

  // Sweeteners & Baking
  sugar: "🍬",
  jaggery: "🟤",
  gur: "🟤",
  honey: "🍯",
  chocolate: "🍫",
  cocoa: "🍫",
  vanilla: "🌿",
  "baking powder": "🥄",
  "baking soda": "🥄",

  // Coconut
  "fresh coconut": "🥥",
  "desiccated coconut": "🥥",
  "coconut powder": "🥥",

  // More Indian vegetables
  "bottle gourd": "🥒",
  lauki: "🥒",
  "bitter gourd": "🥒",
  karela: "🥒",
  "ridge gourd": "🥒",
  tori: "🥒",
  "snake gourd": "🥒",
  "ash gourd": "🥒",
  drumstick: "🌿",
  moringa: "🌿",
  "raw banana": "🍌",
  plantain: "🍌",
  yam: "🍠",
  arbi: "🥔",
  colocasia: "🥔",

  // Drinks
  water: "💧",
  coffee: "☕",
  tea: "🍵",
  "green tea": "🍵",
  juice: "🧃"
};

function IngredientComponent(props) {

  const emoji =
    ingredientEmojis[
      props.ingredientItem.trim().toLowerCase()
    ] || "🥘";

  return (
    <div className="ingredient-card">

      <span className="ingredient-name">
        {props.ingredientItem}
      </span>

      <span className="ingredient-emoji">
        {emoji}
      </span>

      <button
        className="delete-button"
        onClick={() => props.onDelete(props.id)}
      >
        ×
      </button>

    </div>
  );
}

export default IngredientComponent;